FROM openjdk:8-jre
LABEL maintainer="wu812730157@gmail.com"

ADD brand-report-backend-0.0.1-SNAPSHOT.jar /tmp
CMD java -jar /tmp/brand-report-backend-0.0.1-SNAPSHOT.jar
VOLUME /var/log/message/brand-report-backend